

GET http://localhost:3000/api/items/

###

GET http://localhost:3000/api/items/69209cded12c7bce737a3974


###

POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Belay",
    "description": "My test api"
}

###
DELETE http://localhost:3000/api/items/69209c5c8878662925ac60e8


###
PUT http://localhost:3000/api/items/69209b3766a9a78ccd3e06cd
Content-Type: application/json

{
    "name": "Belaynesh",
    "description": "My test api"
}

###

GET http://localhost:3000/api/blog/

###

POST http://localhost:3000/api/blog 
Content-Type: application/json

{
    "title": "A Guide to API Development", 
    "description": "A quick summary of the steps involved in building a simple API with Express and MongoDB.",
    "content": "This is the full, detailed content of the blog post, discussing routing, services, models, and Mongoose validation."
    // If you include 'writer', it must also be in double quotes: "writer": "..."
}
###

GET http://localhost:3000/api/writer/


###
POST http://localhost:3000/api/writer/
Content-Type: application/json

{
    "name": "Petros",
    "age":"34",
    "profession": "Dev"
}